### PR TITLE
Fix various unknown type compilation errors

### PR DESCRIPTION
**Pull request by bradfordboyle**
When compiling Hamlib 4.7 on Alpine Linux, the build fails due to several unknown type errors with the following message:

    error: unknown type name 'mode_t'; did you mean 'rmode_t'?

This commit adjusts the usage of mode_t to rmode_t to fix these compilation errors. With these changes, Hamlib 4.7 builds on Alpine Linux 3.21.6.

See PR #1642 for additional context.

### CODE REVIEW

**Comment by N0NB** [comment]
These other files should likely be corrected as well:

``` console
rigs/icmarine/icm710.h:41:     mode_t mode;
rigs/jrc/jst145.c:69:     mode_t mode;
rigs/yaesu/ft847.c:219:    mode_t mode;
rigs/yaesu/newcat.c:1064:int newcat_60m_exception(RIG *rig, freq_t freq, mode_t mode)
simulators/simic2730.c:26: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic2730.c:27: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic275.c:26: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic275.c:27: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic7000.c:25: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic7000.c:26: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic7100.c:27: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic7100.c:28: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic7200.c:26: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic7200.c:27: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic7300.c:28: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic7300.c:29: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic7600.c:26: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic7600.c:27: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic7610.c:24: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic7610.c:25: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic7700.c:29: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic7700.c:30: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic7851.c:25: mode_t modeA = 1;
simulators/simic7851.c:26: mode_t modeB = 0;
simulators/simic905.c:26: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic905.c:27: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic910.c:27: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic910.c:28: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic9100.c:25: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic9100.c:26: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simic9700.c:26: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simic9700.c:27: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simicgeneric.c:25: mode_t modeA = RIG_MODE_CW;
simulators/simicgeneric.c:26: mode_t modeB = RIG_MODE_USB;
simulators/simicr8600.c:25: mode_t modeA = RIG_MODE_CW;
simulators/simicr8600.c:26: mode_t modeB = RIG_MODE_USB;
simulators/simid5100.c:25: mode_t modeA = RIG_MODE_PKTUSB;
simulators/simid5100.c:26: mode_t modeB = RIG_MODE_PKTUSB;
simulators/simqrplabs.c:242:            mode_t tmpmode = buf[14];
simulators/simtrusdx.c:205:            mode_t tmpmode = buf[14];
simulators/simts450.c:205:            mode_t tmpmode = buf[14];
simulators/simts590.c:285:            mode_t tmpmode = buf[14];
simulators/simts950.c:243:            mode_t tmpmode = buf[14];
simulators/simts990.c:274:            mode_t tmpmode = buf[14];
simulators/simxiegug90.c:24: mode_t modeA = RIG_MODE_CW;
simulators/simxiegug90.c:25: mode_t modeB = RIG_MODE_USB;
simulators/simxiegux108g.c:24: mode_t modeA = RIG_MODE_CW;
simulators/simxiegux108g.c:25: mode_t modeB = RIG_MODE_USB;
simulators/simxiegux6100.c:24: mode_t modeA = RIG_MODE_CW;
simulators/simxiegux6100.c:25: mode_t modeB = RIG_MODE_USB;
src/multicast.c:411:    mode_t modeA, modeAsave = 0;
src/multicast.c:412:    mode_t modeB, modeBsave = 0;
tests/rigctlcom.c:1541:        mode_t mode = 0;
```

Since you're not building the simulators, you didn't catch the others.

All of these usages of `mode_t` should be corrected.

**Comment by GeoBaltz** [comment]
I'm surprised this didn't happen more. I guess there are spurious includes of sys/types.h floating around.

For the simulators though, neither should be used.  I've been on a campaign to separate the simulators from the hamlib definitions - it's too likely that the simulation is of the Hamlib behavior, not the rig. The files outside of simulators/ should definitely be updated.

This change is a good start.

**Comment by bradfordboyle** [comment]
Interestingly, the simulator's compile just find on Alpine Linux. The file `bits/alltypes.h` typedefs `mode_t` as `unsigned`. This header gets pulled in via `stdio.h`.

I've pushed a second commit updating all `mode_t` usage in simulators to `rmode_t` for consistency.

**Comment by N0NB** [comment]
It boils down to helping the people working on the code read it clearly.  Even if the underlying types are compatible, I think that making sure that we use `rmode_t` to reference a radio mode is important.

**Comment by GeoBaltz** [comment]
Yeahbut...
rmode_t is a uint64 bit mask with about 47 modes defined.  No rig will ever have that many, nor will it support multiple modes at the same time.  I worry that the simulators will do something outside of what the real rig can do.  I'd much rather see them limit themselves to only what is possible.

Same goes for VFOs - the Hamlib vfo_t is heavily overloaded with virtual names(RIG_VFO_TX, RIG_VFO_CURR,...) and all possible hardware types(A/B, MAIN/SUB, A/B/C, ...).  The simulators should be written with the H/W possibilities in mind, so they can't handle or return values that the real rig doesn't know about.

**Comment by N0NB** [comment]
The simulators should use a privately defined type that is sensible for their use.  Given that there is a need to have them be separate from the library, this is probably the way to go.

That detail slipped my mind.

Bradford, I'll just merge in your first commit and leave the simulators alone for now.  Based on George's commentary I think that is the proper thing to do with this PR.

**Comment by bradfordboyle** [comment]
I've reverted/removed the commit that updated the code in simulators. Should be good to merge now.

**Comment by N0NB** [comment]
Thanks, Bradford.  Much appreciated.
